### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'fire')

### ISSUE THREAD

**Issue by Ansoriddin0911** [Wildhoney/Leaflet.FreeDraw#197]
Hi.
I'm using Leaflet.FreeDraw with Nuxtjs application.
```
leaflet-freedraw: 2.13.3
nuxt: 2.17.0
```
When I tried to move to another route I came across to this error:
```javascript
TypeError: Cannot read properties of undefined (reading 'fire')
    at updateFor (leaflet-freedraw.web.js:1:361877)
    at e.value (leaflet-freedraw.web.js:1:952119)
    at NewClass.remove (leaflet-src.js:3900:22)
    at VueComponent.beforeDestroy (LMap.js:308:22)
    at invokeWithErrorHandling (vue.runtime.esm.js:3056:61)
    at callHook$1 (vue.runtime.esm.js:4070:13)
    at Vue.$destroy (vue.runtime.esm.js:3841:9)
    at destroy (vue.runtime.esm.js:4480:35)
    at invokeDestroyHook (vue.runtime.esm.js:6733:17)
    at invokeDestroyHook (vue.runtime.esm.js:6739:17)
``` 
The error appears before destroying my component.
In chrome debugger I found that in `updateFor` function `instanceKey` equal to `Symbol(freedraw/instance)`, but in the `t` not such instance
![Group 206](https://github.com/user-attachments/assets/5646fe23-8bf7-4e11-9ef2-43b864d6b4d5)

**Comment by paveleremin** [comment]
@Ansoriddin0911 I have the same issue. Did you solve it?

**Comment by Ansoriddin0911** [comment]
Hi.
I had to solve this problem in a hurry. Due to the limited time, I just cloned this repo and modified line 22 in the [https://github.com/Wildhoney/Leaflet.FreeDraw/blob/master/src/helpers/Layer.js](https://github.com/Wildhoney/Leaflet.FreeDraw/blob/master/src/helpers/Layer.js) file 
from 
`map[instanceKey].fire('markers', { latLngs, eventType });` 
to 
`if(map.hasOwnProperty(instanceKey)) {
        map[instanceKey].fire('markers', { latLngs, eventType });
    }`
By checking if `instanceKey` exists on `map` object, I was able to avoid the issue.

After fixing the issue, I built project in my local PC and placed the built file in my project.
